### ISSUE TITLE
Settings screen line overlap

### ISSUE THREAD

**Issue by 8raveStarr** [Geeksltd/VSIX.TidyCSharp#1]
The lines of the settings screen overlap making them unreadable.

![image](https://user-images.githubusercontent.com/2077877/33573651-130d024c-d8fc-11e7-8407-5feee1db9d8c.png)

**Comment by tohfe** [comment]
What is exact your resolution and scaling in windows?

**Comment by 8raveStarr** [comment]
My resolution is 3840 x 2160 and my scaling is 250%.


________________________________

**Comment by PaymonK** [comment]
Fixed
