### ISSUE TITLE
Attribute removal is too agressive on XmlAttribute

### ISSUE THREAD

**Issue by rtbsoft** [Geeksltd/VSIX.TidyCSharp#3]
XmlAttribute IS the name of the attribute, with its long form being XmlAttributeAttribute.

The process is reducing the name from XmlAttribute to Xml, and that's wrong.

To add insult to injury, it also then removes the associated using statement.

**Comment by tohfe** [comment]
It is fixed now

**Comment by rtbsoft** [comment]
thank you
