### ISSUE TITLE
remove curly braces {} for single line if else 

### ISSUE THREAD

**Issue by mcdon-ron** [Geeksltd/VSIX.TidyCSharp#4]
requesting an option to remove curly braces for code like
```
if(x==y)
{
    DoSomething();
}
else
{
    DoSomethingElse();
}
```
maybe this would be part of the option "Normalize white spaces -> No { and } for short blocks (single statement and < 70 chars)". It's closely related to "Compact small if/else blocks", maybe with an option for multiline rather than single line only.

Thanks

**Comment by PaymonK** [comment]
This is now added
